"""Medical-aware tokenizer owned by the Ragamuffin app layer."""

from __future__ import annotations

import re

# Medical abbreviation expansions add expansion terms to the token stream while
# preserving the original abbreviation for exact lexical matches.
_MEDICAL_ABBREVIATIONS = {
    "icu": ["intensive", "care", "unit"],
    "ed": ["emergency", "department"],
    "er": ["emergency", "room"],
    "bbp": ["bloodborne", "pathogen"],
    "chh": ["childrens", "hospital"],
    "mvp": ["minimum", "viable", "product"],
    "cpr": ["cardiopulmonary", "resuscitation"],
    "iv": ["intravenous"],
    "im": ["intramuscular"],
    "po": ["oral"],
    "prn": ["as", "needed"],
    "bid": ["twice", "daily"],
    "tid": ["three", "times", "daily"],
    "qid": ["four", "times", "daily"],
    "stat": ["immediately"],
    "npo": ["nothing", "by", "mouth"],
    "bpm": ["beats", "per", "minute"],
    "bp": ["blood", "pressure"],
    "hr": ["heart", "rate"],
    "rr": ["respiratory", "rate"],
    "o2": ["oxygen"],
    "spo2": ["oxygen", "saturation"],
    "ekg": ["electrocardiogram"],
    "ecg": ["electrocardiogram"],
    "ct": ["computed", "tomography"],
    "mri": ["magnetic", "resonance"],
    "cbc": ["complete", "blood", "count"],
    "bmp": ["basic", "metabolic", "panel"],
    "abg": ["arterial", "blood", "gas"],
    "wbc": ["white", "blood", "cell"],
    "rbc": ["red", "blood", "cell"],
    "hgb": ["hemoglobin"],
    "hct": ["hematocrit"],
    "plt": ["platelet"],
    "inr": ["international", "normalized", "ratio"],
    "ptt": ["partial", "thromboplastin", "time"],
    "gi": ["gastrointestinal"],
    "gu": ["genitourinary"],
    "cns": ["central", "nervous", "system"],
    "dvt": ["deep", "vein", "thrombosis"],
    "pe": ["pulmonary", "embolism"],
    "ards": ["acute", "respiratory", "distress"],
    "copd": ["chronic", "obstructive", "pulmonary"],
    "chf": ["congestive", "heart", "failure"],
    "mi": ["myocardial", "infarction"],
    "cva": ["cerebrovascular", "accident"],
    "tbi": ["traumatic", "brain", "injury"],
    "dka": ["diabetic", "ketoacidosis"],
    "uti": ["urinary", "tract", "infection"],
    "ppe": ["personal", "protective", "equipment"],
    "phi": ["protected", "health", "information"],
    "hipaa": ["health", "insurance", "portability"],
    "emr": ["electronic", "medical", "record"],
    "ehr": ["electronic", "health", "record"],
    "hpi": ["history", "present", "illness"],
    "ros": ["review", "systems"],
    "wf": ["workflow"],
    "faq": ["frequently", "asked", "questions"],
    "faqs": ["frequently", "asked", "questions"],
}

_STOPWORDS = frozenset(
    {
        "a",
        "an",
        "the",
        "and",
        "or",
        "but",
        "in",
        "on",
        "at",
        "to",
        "for",
        "of",
        "with",
        "by",
        "from",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "being",
        "have",
        "has",
        "had",
        "do",
        "does",
        "did",
        "will",
        "would",
        "shall",
        "should",
        "may",
        "might",
        "must",
        "can",
        "could",
        "that",
        "which",
        "who",
        "whom",
        "this",
        "these",
        "those",
        "what",
        "when",
        "where",
        "why",
        "how",
        "it",
        "its",
        "he",
        "she",
        "they",
        "them",
        "we",
        "you",
        "i",
        "not",
        "no",
        "nor",
        "as",
        "if",
        "then",
        "than",
        "so",
        "up",
        "out",
        "about",
        "into",
        "over",
        "after",
        "before",
        "between",
        "under",
        "above",
        "below",
        "each",
        "every",
        "all",
        "any",
        "both",
        "few",
        "more",
        "most",
        "other",
        "some",
        "such",
        "only",
        "own",
        "same",
        "very",
        "just",
        "also",
        "describe",
        "explain",
    }
)

_TOKEN_RE = re.compile(r"[a-zA-Z0-9]+")


def medical_tokenize(text: str) -> list[str]:
    """Tokenize text with Ragamuffin's clinical vocabulary assumptions."""

    tokens: list[str] = []
    for token in _TOKEN_RE.findall(text.lower()):
        if token in _STOPWORDS:
            continue

        tokens.append(token)
        expansions = _MEDICAL_ABBREVIATIONS.get(token)
        if expansions:
            tokens.extend(expansion for expansion in expansions if expansion not in _STOPWORDS)

    return tokens
